### ISSUE TITLE
Reload custom CSS - HTTP ERROR 500

### ISSUE THREAD

**Issue by DieterReinert** [smogon/pokemon-showdown-client#2119]
Whenever trying to reload custom CSS we get a HTTP ERROR 500.

This started happening after the issue where https://play.pokemonshowdown.com/ was unavailable because they had to move to a new server.

**Comment by monsanto** [comment]
i fixed an error that may be related to this

**Comment by mia-pi-git** [comment]
This is 500'ing because we never set a directory for css on the new loginserver, as far as I can tell. I just set it and rebooted, so it should work now.

**Comment by DieterReinert** [comment]
<img width="566" alt="image" src="https://github.com/smogon/pokemon-showdown-client/assets/24208129/24d9b528-c1f1-4a83-a1ec-27482ebc36eb">

**Comment by DieterReinert** [comment]
The issue is still there...

**Comment by DieterReinert** [comment]
Any update?

**Comment by DieterReinert** [comment]
@mia-pi-git said they were going to look at the php for the customcss, but the issue is still there any idea when we could expect a update on this?

**Comment by monsanto** [comment]
Nobody is currently working on this, sorry. Maybe @Zarel will fix it

**Comment by monsanto** [comment]
Someone tagged me about this so I took a second to see what it is. My guess is that the CSS sanitizer library doesn't play nicely with the version of PHP we're using (8.1.2). 

The error is
> PHP Parse error:  syntax error, unexpected token "match", expecting variable in lib/css-sanitizer/Wikimedia/CSS/Grammar/Matcher.php on line 121

Maybe this will give a starting point for someone to fix this error. Sorry I cannot be of more help.

**Comment by DieterReinert** [comment]
@monsanto @Zarel it is becasue "Match" in php 8+ is a keyword. If you look at line 121:
private static function collectSignificantWhitespace( Match $match, &$ret = [] ) {

It uses Match as a type here which is not allowed in PHP 8+.

In the update code (found here: https://github.com/wikimedia/css-sanitizer/tree/master/src) it is like this:
private static function markSignificantWhitespace( $list, $match, $significantWS, $end ) {

Which should solve the issue potentially.

**Comment by monsanto** [comment]
A PR that renames the new keyword may be the easiest fix, if someone wants to do it.

**Comment by Starmys** [comment]
https://github.com/smogon/pokemon-showdown-client/pull/2126
Tried to fix it by upgrading the library.

**Comment by DieterReinert** [comment]
Same error is back, might be due to the recent refactors

**Comment by Zarel** [comment]
(Fixed again in bd134f4ccf541378979c.)
